version: '3'

services:
  gpt-pilot:
    environment:
      - ENDPOINT=OPENAI
      - MODEL_NAME=gpt-4
      - MAX_TOKENS=8192
      - DATABASE_TYPE=postgres
      - DB_NAME=pilot
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=pilot
      - DB_PASSWORD=pilot
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - IGNORE_PATHS=folder1,folder2
    volumes:
      - ~/gpt-pilot-workspace:/usr/src/app/workspace
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7681:768
